
# BUILDSPEC ON AMAZON LINUX2

version: 0.2

env:
  variables:
    CFNLINT_HOME: "/home/ec2-user/.local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
  parameter-store:
    DB_UN: DatabaseUserName         # THE CODEBUILD SERVICE ROLE WHILE CREATING THE PIPELINE SHOULD HAVE 
    DB_PW: databasePassword

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - aws --version
      - python3 --version  
      - pip3 --version
  build:
    commands:
      - echo Build started on `date`
      - sudo yum update -y
      - echo installing cfn-lint
      - pip3 install cfn-lint
      - echo validate cfn template 
      - cfn-lint testing-infra.yaml
      - echo package the cfn template
      - aws cloudformation package --template-file testing-infra.yaml --s3-bucket mynewestfirstbucket --output-template-file testing-infra-artifacts.yaml
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - testing-infra.yaml
    - testing-infra-artifacts.yaml
